### ISSUE TITLE
Kanban Board - Setup - Module 2 - Group Capstone Project

### ISSUE THREAD

**Issue by ITurres** [ITurres/TVmaze-movies-website#21]
##  Team Members:
- @Ruthmy 
- @ITurres
 
---

Hey there! I hope all is well.

Here is the link to our Project: [TVmaze-movies-website / Project](https://github.com/ITurres/TVmaze-movies-website/projects/1)
In this case, we are a group of two people.

Thank you very much for your review ✨

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @ITurres & @Ruthmy  👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Proper template is used ✔
- Kanban is setup properly✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ITurres** [comment]
Thank you @AbelG101 for reviewing this issue! 😃 Have a great day and happy coding!
